# Dependency Review Configuration
fail-on-severity: moderate
fail-on-scopes:
  - runtime
  - development
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MPL-2.0
deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-1.0
  - AGPL-3.0
allow-dependencies-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MPL-2.0